//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainRealEstate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REALSTATEEntities : DbContext
    {
        public REALSTATEEntities()
            : base("name=REALSTATEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_Booking> TBL_Booking { get; set; }
        public DbSet<TBL_Contact1> TBL_Contact1 { get; set; }
        public DbSet<TBL_Login> TBL_Login { get; set; }
        public DbSet<TBL_Registration> TBL_Registration { get; set; }
    }
}
