//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainRealEstate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Booking
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string MinRent { get; set; }
        public string MaxRent { get; set; }
        public string Flat { get; set; }
        public string Perpose { get; set; }
        public string City { get; set; }
        public string Number { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Profession { get; set; }
        public string ArrvDate { get; set; }
        public string DeptvDate { get; set; }
        public string BookingDate { get; set; }
    }
}
